version: '3'

services:
  talker:
    build: .
    command: ros2 run demo_nodes_cpp talker

  listener:
    build: .
    environment:
      - "PYTHONUNBUFFERED=1"
    command: ros2 run demo_nodes_py listener
