version: '3'

services:
  talker:
    image: ros:humble
    volumes:
      - "./ws_src/talker:/dev_ws/src/talker"
    command: bash /dev_ws/src/talker/build_and_run_talker.sh

  listener:
    image: ros:humble
    volumes:
      - "./ws_src/listener:/dev_ws/src/listener"
    command: bash /dev_ws/src/listener/build_and_run_listener.sh
